### ISSUE TITLE
File on different Drive not encrypting | Sytem Volume Information issue

### ISSUE THREAD

**Issue by TrevorCEH** [hackthedev/teardrop#7]
I have tested your latest released (teardrop-2.1.1) and today's updated repository also.
**1.This was my configuration Just little change of these text.**
![1_ Config](https://user-images.githubusercontent.com/45958463/124971618-3d447e00-e04b-11eb-8762-56208f4ede16.png)

**2.If I just copy (teardrop.exe) in my desktop and click (with/without Admin privileges) for run It doesn't run.It shows this Error.But when I copy full Debug/Release directory into desktop and click on(teardrop.exe) from folder with/without Admin privileges It runs and works perfectly.If It possible please make it in single *.exe  file.**
![2__When Only exe](https://user-images.githubusercontent.com/45958463/124971674-4e8d8a80-e04b-11eb-95b7-8725a61c7e3f.png)

**3.After successfully Encrypted all files It doesn't create any *.txt  or *.html  files in desktop.**
**4. But All files from Downloads/Music/Pictures/videos and All others Drives/Connected Devices remain unchanged.You can see some of my test screenshot here.** 

![Drive](https://user-images.githubusercontent.com/45958463/124971821-7c72cf00-e04b-11eb-94eb-0525c2071539.png)
![Only Desktop Folder_](https://user-images.githubusercontent.com/45958463/124971837-7ed52900-e04b-11eb-9a2d-1f291eef6ae7.png)
![Screenshot_2](https://user-images.githubusercontent.com/45958463/124971840-7ed52900-e04b-11eb-81ad-746d7bcca8e4.png)

**Comment by hackthedev** [comment]
## About learning new Things
Back in the day when i started programming I learned from a Ransomware Project called "Hiddentear". I learned a lot there. Thats why i wanted to make my own Ransomware project so that people might learn new things too like i did.

## Part 2
Yeah the "problem" is that if you copy `teardrop.exe` to any other location without the `.dll` files it will fail. I might be able to merge this, but when this happenes I usually make an SFX WinRAR Archive. It basically lets you create a WinRAR Archive with special features like "Execute after Extraction" and it saves as runnable `.exe` File, so you could merge them all into one exe file.

This is at least how I dealed with it in the past.

## Part 3
I know this issue where it skips paths when they encounter some error. I fixed it some time ago and it did work but it seems like now its not anymore or at least in your case. I will check that again and also investigate about why i.e. `Downloads` is not being encrypted.

## Links
[WinRAR SFX Tutorial](https://www.isunshare.com/blog/how-to-create-sfx-archive-with-winrar-and-7zip/)
("Execute after Extraction" should be covered in the Tab "Setup").

**Comment by hackthedev** [comment]
Oh and by the way in the application folder should be a file named "log.txt". you might want to post it too so i can see whats going on

**Comment by TrevorCEH** [comment]
**I am sorry for late.I was in sleep.We are not in same time zone.Here is the log file.Please,check it**
[log.txt](https://github.com/hackthedev/teardrop/files/6790039/log.txt)

**Comment by hackthedev** [comment]
Okay the reason why it didn't create any message file on the drives was also because `The device is not ready.` (Thats one error).

Also it didn't encrpt the other drives because the <br>`Access to the path 'R:\' is denied.` and <br>`Access to the path 'Z:\' is denied.`

<br>

Log file text:
> GetFiles > Create Message File ]=================================
> The device is not ready.
> 
> 
> ShowAllFolderUnder > General Error ]=================================
> The device is not ready.
> 
> 
> GetFiles > Create Message File ]=================================
> Access to the path 'R:\' is denied.
> 
> ShowAllFolderUnder > General Error ]=================================
> Access to the path 'R:\System Volume Information' is denied.
> 
> GetFiles > Create Message File ]=================================
> Access to the path 'Z:\' is denied.
> 
> ShowAllFolderUnder > General Error ]=================================
> Access to the path 'Z:\System Volume Information' is denied.

<br>

Basically the program never had any permission to do anything with those drives. I don't know why this happened in your case, but i will investigate this issue. Its possible that this issue is only happening on your machine, but we are going to figure it out anyway ;-)

I will keep you updated, @TrevorCEH .

**Comment by TrevorCEH** [comment]
**I have tasted the same compiled file in ( windows 8.1  64 bit -single language Build 9600) and I have seen nearly same things happen like windows 10 pro 64-bit .**

**1. In This machine I can right click on mouse that was not possible in windows 10 .**

![121](https://user-images.githubusercontent.com/45958463/125130639-2709f100-e123-11eb-9dd0-1ec1ab61b02f.png)

![referesh](https://user-images.githubusercontent.com/45958463/125130458-d5616680-e122-11eb-97ab-ae3b3b4eb1d7.png)

**2.  All desktop files got 100% encrypted  and some files from download folder also** 

![some files](https://user-images.githubusercontent.com/45958463/125130698-3be68480-e123-11eb-9a27-9c3c741643db.png)

**3. Others drive remain unchanged** 

![Unchanged](https://user-images.githubusercontent.com/45958463/125130767-5e789d80-e123-11eb-88f4-82e50c607f54.png)

**4.  log file may be empty or some space  I have got. Here is log file**

[log.txt](https://github.com/hackthedev/teardrop/files/6793732/log.txt)

**Comment by hackthedev** [comment]
Thank you for testing it.

It seems like its still unable to encrypt other drives. I will try finding the issue in the program and fix it tomorrow. at least thats what i plan.

When I find something new i'll gonna let you know ;-)

**Comment by hackthedev** [comment]
@TrevorCEH i might've found the issue why some files in the directory remained unchanged. If you look [at this line](https://github.com/hackthedev/teardrop/blob/master/teardrop/teardrop/Form1.cs#L220), it checks if the file's extension is the same as one of those saved in the array, but i forgot to add the `.toLower()` on `ext`. Thats why the Images that have the PNG extension in caps were not encrypted.

Im currently updating it and i already took care of that.

<br>

Broken Line of Code:
```csharp
if (validExtensions.Contains(ext))
```

How it should be:
```csharp
if (validExtensions.Contains(ext.ToLower()))
```

**Comment by TrevorCEH** [comment]
**I have replaced (https://github.com/hackthedev/teardrop/blob/master/teardrop/teardrop/Form1.cs#L220) this line with this line * if (validExtensions.Contains(ext.ToLower())) * and nearly same things happen.**

**Note: I believe file extention is not  the reason for unencrypt others drivers. I have found  ( *.exe) extention is not included in your code but It also encrypted.**
![Extentions](https://user-images.githubusercontent.com/45958463/125206259-2b134b80-e2a8-11eb-95f1-c715956ece91.png)

![Extentions_](https://user-images.githubusercontent.com/45958463/125206377-ce646080-e2a8-11eb-9cf7-8b4b2cb1ee0f.png)

**Comment by TrevorCEH** [comment]
Here is the log file you can check it,If you have some times
[log.txt](https://github.com/hackthedev/teardrop/files/6797485/log.txt)

**Comment by hackthedev** [comment]
Im not blaming the file extension to break the encryption of other hard drives but general encryption. Im still investigating the issue related to the drives not being ready therefore not being encrypted

**Comment by hackthedev** [comment]
Hello @TrevorCEH . I've updated it. Its kind of fixed. Well at least it encrypted one drive but not the other one. Its kind of buggy. I honestly dont know why this is happening. 

I will still investigate on this issue.
